
# tap repositories and their packages

tap homebrew/core
brew docbook
brew autossh
brew ipython@5
brew brew-gem
brew cheat
brew jpeg
brew libvpx
brew spidermonkey
brew zsh-completions
brew thefuck
brew libgpg-error
brew s-lang
brew mysql
brew libsamplerate
brew x265
brew gdbm
brew checkbashisms
brew pango
brew libvo-aacenc
brew gobject-introspection
brew libsndfile
brew libdvdcss
brew tcl-tk
brew nspr
brew leptonica
brew fontconfig
brew lv
brew clang-format
brew snappy
brew htop-osx
brew gmp
brew norm
brew pixman
brew freetype
brew youtube-dl
brew python
brew libidn
brew latex2rtf
brew libtermkey
brew mpv
brew libbluray
brew frei0r
brew libglade
brew tmux --HEAD
brew gtk+
brew openjpeg
brew rtmpdump
brew pyenv-virtualenv
brew python3
brew neovim
brew zsh
brew libcaca
brew makedepend
brew libyaml
brew autojump
brew fftw
brew unrar
brew libaacs
brew gd
brew glfw
brew mercurial
brew redpen
brew libvorbis
brew cscope
brew colordiff
brew pkg-config
brew shared-mime-info
brew wdiff
brew checkstyle
brew libdvdread
brew cairo
brew py2cairo
brew libbs2b
brew go
brew webp
brew jemalloc
brew protobuf
brew texi2html
brew msgpack
brew vimpager
brew reattach-to-user-namespace
brew yasm
brew automake
brew lua
brew librsvg
brew libpng
brew xvid
brew boost
brew libsodium
brew imagemagick
brew libpgm
brew cmatrix
brew libvidstab
brew vapoursynth
brew jq
brew pygtk --with-libglade
brew asciidoc
brew maven
brew ranger
brew pygobject
brew wget
brew spark
brew bazaar
brew isl@0.12
brew libgcrypt
brew bash
brew midnight-commander
brew sphinx-doc
brew iperf3
brew autoconf
brew root
brew pandoc
brew atk
brew icu4c
brew utf8proc
brew x264
brew isl
brew libtool
brew giflib
brew tesseract
brew openh264
brew schroedinger
brew libass
brew bison
brew nasm
brew nmap
brew dcadec
brew libtiff
brew hicolor-icon-theme
brew harfbuzz
brew vim --with-lua
brew xz
brew jbig2dec
brew graphviz
brew perl
brew pcre
brew libssh2
brew git
brew pv
brew gdk-pixbuf
brew w3m
brew m-cli
brew pyenv
brew opus
brew emacs --with-cocoa
brew gmp@4
brew ctags
brew zeromq
brew gnu-getopt
brew glib
brew mackup
brew theora
brew ccat
brew nkf
brew libmpc
brew gibo
brew opencore-amr
brew graphite2
brew doxygen
brew imlib2
brew flac
brew libevent
brew cloog
brew ruby
brew peco
brew dash
brew ffmpeg
brew shellcheck
brew tree
brew libsoxr
brew faac
brew bdw-gc
brew lynx
brew highlight
brew z
brew fdk-aac
brew sqlite
brew multitail
brew libxml2
brew libcroco
brew openssl
brew ant
brew socat
brew orc
brew gcc
brew libssh
brew cmake
brew hub
brew md5sha1sum
brew lame
brew hugo
brew libdvdnav
brew gettext
brew brew-pip
brew coreutils
brew source-highlight
brew tig
brew node
brew mas
brew libvterm
brew little-cms2
brew rubberband
brew unixodbc
brew zimg
brew bash-completion
brew mosh
brew xrootd
brew unibilium
brew libogg
brew lesspipe
brew lastpass-cli
brew openssl@1.1
brew libffi
brew oniguruma
brew readline
brew jupyter
brew fribidi
brew jp2a
brew gsl
brew vnu
brew sl
brew fdupes
brew libuv
brew mpfr

tap homebrew/x11

tap caskroom/fonts
cask font-hack-nerd-font

tap caskroom/cask
cask imageoptim
cask adobe-illustrator-cc
cask teamviewer
cask mendeley-desktop
cask qlmarkdown
cask configure-application-dock-tile
cask jupyter-notebook-ql
cask unetbootin
cask xrg
cask geektool
cask macvim
cask vlc
cask skype
cask inkscape
cask appcleaner
cask karabiner-elements
cask qlvideo
cask suspicious-package
cask simplefloatingclock
cask dupscanub
cask evernote
cask liteicon
cask ifunbox
cask the-unarchiver
cask keycastr
cask iterm2
cask dropbox
cask macs-fan-control
cask betterzipql
cask cathode
cask cooviewer
cask free-ruler
cask mono-mdk
cask docker
cask adobe-creative-cloud
cask libreoffice
cask quicklookase
cask clipy
cask gimp
cask caffeine
cask madruby
cask qlprettypatch
cask timer
cask quicklook-json
cask image2icon
cask qlstephen
cask webpquicklook
cask qlcolorcode
cask silverlight
cask mactex
cask horndis
cask qlimagesize
cask firefox
cask adobe-acrobat-reader
cask hyperswitch
cask google-chrome
cask xquartz
cask league-of-legends
cask google-japanese-ime
cask key-codes
cask quicklook-csv
cask java
cask waterfox
cask controlplane
cask bathyscaphe
cask flip4mac
cask licecap
cask bettertouchtool
cask skitch

tap rcmdnk/file
brew brew-file

tap rcmdnk/rcmdnkpac
brew screenutf8 --utf8

tap rcmdnk/rcmdnkcask
cask font-migu1m
cask menubargmail

# App Store applications
appstore 451732904 App Language Chooser (1.0)
appstore 430173763 Degrees (4.2.1)
appstore 458998390 Farensius (2.0.2)
appstore 682658836 GarageBand (10.2.0)
appstore 408981434 iMovie (10.1.7)
appstore 409183694 Keynote (7.3)
appstore 539883307 LINE (5.3.3)
appstore 409203825 Numbers (4.3)
appstore 409201541 Pages (6.3)
appstore 487505968 Photobricks (1.6)
appstore 568494494 Pocket (1.6.6)
appstore 560851219 Should I Sleep (1.8.4)
appstore 495705418 Volume Reset (1.3)
appstore 495945638 Wake Up Time (1.4)
appstore 497799835 Xcode (9.0)
