# Tap repositories and their packages
tap 'rcmdnk/brewall'
brew 'brewall'

# Cask packages

# Other Homebrew packages
brew 'autoconf'
brew 'bash-completion'
brew 'bdw-gc'
brew 'boost'
brew 'checkbashisms'
brew 'colordiff'
brew 'cscope'
brew 'freetype'
brew 'gdbm'
brew 'git'
brew 'imagemagick'
brew 'jpeg'
brew 'libevent'
brew 'libpng'
brew 'libtool'
brew 'lua'
brew 'macvim --with-lua'
brew 'mercurial'
brew 'pkg-config'
brew 'python'
brew 'readline'
brew 'sqlite'
brew 'stow'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'w3m'
brew 'wdiff'
brew 'xz'
